
name: Caller WF For .Net App

on:
  workflow_dispatch:

jobs:
  caller-workflow:
      name: Build .Net app
      uses: MohithPilli/Reusable-Workflows/.github/workflows/app-main.yml@main
      with:
        runs-on: ubuntu-latest
        run-tests: false
        project-folder: .
        artifact-name: drop-ubuntu

    
            
