
name: Caller Workflow For .Net App

on:
  workflow_dispatch:
 # push:
 #   branches:
 #   - main

jobs:
  caller-workflow:
      name: Build app on Ubuntu
      uses: missAnkita/Reusable-Workflows/.github/workflows/dotnet-reusable-workflow.yml@main
      with:
        runs-on: ubuntu-latest
        run-tests: false
        #project-folder: src
        project-folder: .
        artifact-name: drop-ubuntu

    
            

